"""星点自动匹配与序列匹配共享的业务常量。"""

from __future__ import annotations


# 自动匹配候选星的最暗星等上限与最低高度角。
AUTO_MATCH_SEARCH_MAG_LIMIT = 8.0
AUTO_MATCH_MIN_ALTITUDE_DEG = -5.0

# 拟合约束模式及软约束默认权重。
AUTO_MATCH_CONSTRAINT_ANCHOR = "anchor"
AUTO_MATCH_CONSTRAINT_SOFT = "soft"
AUTO_MATCH_CONSTRAINT_MODES = (
    AUTO_MATCH_CONSTRAINT_ANCHOR,
    AUTO_MATCH_CONSTRAINT_SOFT,
)
AUTO_MATCH_DEFAULT_SOFT_WEIGHT = 0.3

# 星点检测、去重和标注限制。
AUTO_MATCH_MIN_AMPLITUDE = 2.0
AUTO_MATCH_DUPLICATE_MIN_DISTANCE_PX = 4.0
AUTO_MATCH_ANNOTATION_LIMIT = 250

# 自动补充候选按图像网格轮询，避免匹配点集中在少数亮星区域。
AUTO_MATCH_FILL_GRID_COLUMNS = 5
AUTO_MATCH_FILL_GRID_ROWS = 4

# 星点拟合和参考星点选参数。
MIN_PSF_RADIUS_PX = 4
REFERENCE_STAR_PICK_SCREEN_RADIUS_PX = 32
