from __future__ import annotations

from PyQt5.QtCore import Qt

from .matching_constants import AUTO_MATCH_FILL_GRID_COLUMNS, AUTO_MATCH_FILL_GRID_ROWS


SEQUENCE_MIN_PAIR_FRACTION = 0.80
# 达到可靠下限后只保留少量冗余，避免为补齐第一帧全部星点扫描暗星。
SEQUENCE_PAIR_SAFETY_MARGIN = 6
# 保留序列模块原有名称，并与星点匹配页共用同一套网格规格。
SEQUENCE_FILL_GRID_COLUMNS = AUTO_MATCH_FILL_GRID_COLUMNS
SEQUENCE_FILL_GRID_ROWS = AUTO_MATCH_FILL_GRID_ROWS
# 补充候选按小批次检测，当前批次补足目标后立即停止。
SEQUENCE_SUPPLEMENTAL_BATCH_SIZE = 64
SEQUENCE_SUPPLEMENTAL_FIT_WEIGHT = 0.5
SEQUENCE_SUPPLEMENTAL_PAIR_ORIGIN = "auto_match"

IMAGE_SEQUENCE_INDEX_COLUMN = 0
IMAGE_SEQUENCE_NAME_COLUMN = 1
IMAGE_SEQUENCE_DELTA_T_RMS_COLUMN = 2
IMAGE_SEQUENCE_POSE_RMS_COLUMN = 3
IMAGE_SEQUENCE_REFIT_RMS_COLUMN = 4
# 兼容既有调用；序列主残差列现明确表示仅做 δt 修正后的 RMS。
IMAGE_SEQUENCE_RMS_COLUMN = IMAGE_SEQUENCE_DELTA_T_RMS_COLUMN
IMAGE_SEQUENCE_PATH_ROLE = Qt.UserRole + 20
IMAGE_SEQUENCE_INDEX_ROLE = Qt.UserRole + 21
IMAGE_SEQUENCE_RMS_ROLE = Qt.UserRole + 22
IMAGE_SEQUENCE_SORT_KEY_INDEX = "index"
IMAGE_SEQUENCE_SORT_KEY_RMS = "rms"
IMAGE_SEQUENCE_SORTABLE_COLUMNS = {
    IMAGE_SEQUENCE_INDEX_COLUMN: IMAGE_SEQUENCE_SORT_KEY_INDEX,
    IMAGE_SEQUENCE_RMS_COLUMN: IMAGE_SEQUENCE_SORT_KEY_RMS,
}
IMAGE_SEQUENCE_PREVIEW_CACHE_LIMIT = 12
IMAGE_SEQUENCE_MASK_CACHE_LIMIT = 24
IMAGE_SEQUENCE_IMPORT_PROGRESS_MIN_VISIBLE_MS = 500
