# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoralign/ui/catalog_download_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogDownloadDialog(object):
    def setupUi(self, CatalogDownloadDialog):
        CatalogDownloadDialog.setObjectName("CatalogDownloadDialog")
        CatalogDownloadDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CatalogDownloadDialog.resize(560, 230)
        self.verticalLayout = QtWidgets.QVBoxLayout(CatalogDownloadDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelStatus = QtWidgets.QLabel(CatalogDownloadDialog)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        self.labelCurrentTitle = QtWidgets.QLabel(CatalogDownloadDialog)
        self.labelCurrentTitle.setObjectName("labelCurrentTitle")
        self.verticalLayout.addWidget(self.labelCurrentTitle)
        self.progressBarCurrent = QtWidgets.QProgressBar(CatalogDownloadDialog)
        self.progressBarCurrent.setProperty("value", 0)
        self.progressBarCurrent.setObjectName("progressBarCurrent")
        self.verticalLayout.addWidget(self.progressBarCurrent)
        self.labelTotalTitle = QtWidgets.QLabel(CatalogDownloadDialog)
        self.labelTotalTitle.setObjectName("labelTotalTitle")
        self.verticalLayout.addWidget(self.labelTotalTitle)
        self.progressBarTotal = QtWidgets.QProgressBar(CatalogDownloadDialog)
        self.progressBarTotal.setProperty("value", 0)
        self.progressBarTotal.setObjectName("progressBarTotal")
        self.verticalLayout.addWidget(self.progressBarTotal)
        self.labelSpeed = QtWidgets.QLabel(CatalogDownloadDialog)
        self.labelSpeed.setObjectName("labelSpeed")
        self.verticalLayout.addWidget(self.labelSpeed)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutButtons.addItem(spacerItem)
        self.pushButtonClose = QtWidgets.QPushButton(CatalogDownloadDialog)
        self.pushButtonClose.setEnabled(False)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayoutButtons.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)

        self.retranslateUi(CatalogDownloadDialog)
        QtCore.QMetaObject.connectSlotsByName(CatalogDownloadDialog)

    def retranslateUi(self, CatalogDownloadDialog):
        _translate = QtCore.QCoreApplication.translate
        CatalogDownloadDialog.setWindowTitle(_translate("CatalogDownloadDialog", "下载星表"))
        self.labelStatus.setText(_translate("CatalogDownloadDialog", "准备下载星表..."))
        self.labelCurrentTitle.setText(_translate("CatalogDownloadDialog", "当前星表：-"))
        self.labelTotalTitle.setText(_translate("CatalogDownloadDialog", "总进度：-"))
        self.labelSpeed.setText(_translate("CatalogDownloadDialog", "下载速度：-"))
        self.pushButtonClose.setText(_translate("CatalogDownloadDialog", "关闭"))
