# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoralign/ui/image_group_assistant_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageGroupAssistantDialog(object):
    def setupUi(self, ImageGroupAssistantDialog):
        ImageGroupAssistantDialog.setObjectName("ImageGroupAssistantDialog")
        ImageGroupAssistantDialog.resize(520, 560)
        ImageGroupAssistantDialog.setMinimumSize(QtCore.QSize(480, 360))
        ImageGroupAssistantDialog.setMaximumSize(QtCore.QSize(640, 16777215))
        self.verticalLayoutImageGroupAssistant = QtWidgets.QVBoxLayout(ImageGroupAssistantDialog)
        self.verticalLayoutImageGroupAssistant.setObjectName("verticalLayoutImageGroupAssistant")
        self.checkBoxAutoSelectReference = QtWidgets.QCheckBox(ImageGroupAssistantDialog)
        self.checkBoxAutoSelectReference.setEnabled(False)
        self.checkBoxAutoSelectReference.setObjectName("checkBoxAutoSelectReference")
        self.verticalLayoutImageGroupAssistant.addWidget(self.checkBoxAutoSelectReference)
        self.labelImageGroupHint = QtWidgets.QLabel(ImageGroupAssistantDialog)
        self.labelImageGroupHint.setWordWrap(True)
        self.labelImageGroupHint.setObjectName("labelImageGroupHint")
        self.verticalLayoutImageGroupAssistant.addWidget(self.labelImageGroupHint)
        self.tableWidgetImageGroup = QtWidgets.QTableWidget(ImageGroupAssistantDialog)
        self.tableWidgetImageGroup.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetImageGroup.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetImageGroup.setAlternatingRowColors(True)
        self.tableWidgetImageGroup.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetImageGroup.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetImageGroup.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetImageGroup.setRowCount(0)
        self.tableWidgetImageGroup.setColumnCount(5)
        self.tableWidgetImageGroup.setObjectName("tableWidgetImageGroup")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(4, item)
        self.tableWidgetImageGroup.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetImageGroup.verticalHeader().setVisible(False)
        self.verticalLayoutImageGroupAssistant.addWidget(self.tableWidgetImageGroup)
        self.actionSelectAsReference = QtWidgets.QAction(ImageGroupAssistantDialog)
        self.actionSelectAsReference.setObjectName("actionSelectAsReference")

        self.retranslateUi(ImageGroupAssistantDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageGroupAssistantDialog)

    def retranslateUi(self, ImageGroupAssistantDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageGroupAssistantDialog.setWindowTitle(_translate("ImageGroupAssistantDialog", "图像组助手"))
        self.checkBoxAutoSelectReference.setToolTip(_translate("ImageGroupAssistantDialog", "双击切换图像时，自动选取拍摄时间最近且已有 model.json 的其他图像作为参考。"))
        self.checkBoxAutoSelectReference.setText(_translate("ImageGroupAssistantDialog", "自动选取参考"))
        self.labelImageGroupHint.setText(_translate("ImageGroupAssistantDialog", "双击任意图像即可跳转到该图像。"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(0)
        item.setText(_translate("ImageGroupAssistantDialog", "文件名"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(1)
        item.setText(_translate("ImageGroupAssistantDialog", "匹配"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(2)
        item.setText(_translate("ImageGroupAssistantDialog", "映射"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(3)
        item.setText(_translate("ImageGroupAssistantDialog", "蒙版"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(4)
        item.setText(_translate("ImageGroupAssistantDialog", "预览"))
        self.actionSelectAsReference.setText(_translate("ImageGroupAssistantDialog", "选取为参考"))
