# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoralign/ui/image_preview_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImagePreviewDialog(object):
    def setupUi(self, ImagePreviewDialog):
        ImagePreviewDialog.setObjectName("ImagePreviewDialog")
        ImagePreviewDialog.resize(800, 560)
        ImagePreviewDialog.setMinimumSize(QtCore.QSize(480, 320))
        self.verticalLayoutImagePreview = QtWidgets.QVBoxLayout(ImagePreviewDialog)
        self.verticalLayoutImagePreview.setObjectName("verticalLayoutImagePreview")
        self.labelImageName = QtWidgets.QLabel(ImagePreviewDialog)
        self.labelImageName.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.labelImageName.setObjectName("labelImageName")
        self.verticalLayoutImagePreview.addWidget(self.labelImageName)
        self.graphicsViewImagePreview = QtWidgets.QGraphicsView(ImagePreviewDialog)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsViewImagePreview.setBackgroundBrush(brush)
        self.graphicsViewImagePreview.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsViewImagePreview.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsViewImagePreview.setObjectName("graphicsViewImagePreview")
        self.verticalLayoutImagePreview.addWidget(self.graphicsViewImagePreview)

        self.retranslateUi(ImagePreviewDialog)
        QtCore.QMetaObject.connectSlotsByName(ImagePreviewDialog)

    def retranslateUi(self, ImagePreviewDialog):
        _translate = QtCore.QCoreApplication.translate
        ImagePreviewDialog.setWindowTitle(_translate("ImagePreviewDialog", "图像预览"))
        self.labelImageName.setText(_translate("ImagePreviewDialog", "未加载图像"))
