# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoralign/ui/meteor_shower_selection_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeteorShowerSelectionDialog(object):
    def setupUi(self, MeteorShowerSelectionDialog):
        MeteorShowerSelectionDialog.setObjectName("MeteorShowerSelectionDialog")
        MeteorShowerSelectionDialog.resize(900, 470)
        self.verticalLayoutMeteorSelection = QtWidgets.QVBoxLayout(MeteorShowerSelectionDialog)
        self.verticalLayoutMeteorSelection.setObjectName("verticalLayoutMeteorSelection")
        self.labelActiveDate = QtWidgets.QLabel(MeteorShowerSelectionDialog)
        self.labelActiveDate.setObjectName("labelActiveDate")
        self.verticalLayoutMeteorSelection.addWidget(self.labelActiveDate)
        self.labelMeteorSelectionHint = QtWidgets.QLabel(MeteorShowerSelectionDialog)
        self.labelMeteorSelectionHint.setWordWrap(True)
        self.labelMeteorSelectionHint.setObjectName("labelMeteorSelectionHint")
        self.verticalLayoutMeteorSelection.addWidget(self.labelMeteorSelectionHint)
        self.tableWidgetMeteorShowers = QtWidgets.QTableWidget(MeteorShowerSelectionDialog)
        self.tableWidgetMeteorShowers.setAlternatingRowColors(True)
        self.tableWidgetMeteorShowers.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidgetMeteorShowers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetMeteorShowers.setColumnCount(6)
        self.tableWidgetMeteorShowers.setObjectName("tableWidgetMeteorShowers")
        self.tableWidgetMeteorShowers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMeteorShowers.setHorizontalHeaderItem(5, item)
        self.verticalLayoutMeteorSelection.addWidget(self.tableWidgetMeteorShowers)
        self.horizontalLayoutMeteorSelectionButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMeteorSelectionButtons.setObjectName("horizontalLayoutMeteorSelectionButtons")
        self.pushButtonSelectAllMeteorShowers = QtWidgets.QPushButton(MeteorShowerSelectionDialog)
        self.pushButtonSelectAllMeteorShowers.setObjectName("pushButtonSelectAllMeteorShowers")
        self.horizontalLayoutMeteorSelectionButtons.addWidget(self.pushButtonSelectAllMeteorShowers)
        self.pushButtonClearMeteorShowers = QtWidgets.QPushButton(MeteorShowerSelectionDialog)
        self.pushButtonClearMeteorShowers.setObjectName("pushButtonClearMeteorShowers")
        self.horizontalLayoutMeteorSelectionButtons.addWidget(self.pushButtonClearMeteorShowers)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMeteorSelectionButtons.addItem(spacerItem)
        self.pushButtonCancelMeteorSelection = QtWidgets.QPushButton(MeteorShowerSelectionDialog)
        self.pushButtonCancelMeteorSelection.setObjectName("pushButtonCancelMeteorSelection")
        self.horizontalLayoutMeteorSelectionButtons.addWidget(self.pushButtonCancelMeteorSelection)
        self.pushButtonAcceptMeteorSelection = QtWidgets.QPushButton(MeteorShowerSelectionDialog)
        self.pushButtonAcceptMeteorSelection.setDefault(True)
        self.pushButtonAcceptMeteorSelection.setObjectName("pushButtonAcceptMeteorSelection")
        self.horizontalLayoutMeteorSelectionButtons.addWidget(self.pushButtonAcceptMeteorSelection)
        self.verticalLayoutMeteorSelection.addLayout(self.horizontalLayoutMeteorSelectionButtons)

        self.retranslateUi(MeteorShowerSelectionDialog)
        self.pushButtonCancelMeteorSelection.clicked.connect(MeteorShowerSelectionDialog.reject) # type: ignore
        self.pushButtonAcceptMeteorSelection.clicked.connect(MeteorShowerSelectionDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MeteorShowerSelectionDialog)

    def retranslateUi(self, MeteorShowerSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        MeteorShowerSelectionDialog.setWindowTitle(_translate("MeteorShowerSelectionDialog", "选择要渲染的流星雨"))
        self.labelActiveDate.setText(_translate("MeteorShowerSelectionDialog", "全年流星雨"))
        self.labelMeteorSelectionHint.setText(_translate("MeteorShowerSelectionDialog", "活动期、峰值辐射点和 ZHR 采用 IMO 2026 日历。辐射点会随日期漂移，此版本先使用峰值附近坐标作为取景参考。"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(0)
        item.setText(_translate("MeteorShowerSelectionDialog", "渲染"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(1)
        item.setText(_translate("MeteorShowerSelectionDialog", "流星雨"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(2)
        item.setText(_translate("MeteorShowerSelectionDialog", "活动期"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(3)
        item.setText(_translate("MeteorShowerSelectionDialog", "峰值 ZHR"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(4)
        item.setText(_translate("MeteorShowerSelectionDialog", "峰值辐射点"))
        item = self.tableWidgetMeteorShowers.horizontalHeaderItem(5)
        item.setText(_translate("MeteorShowerSelectionDialog", "渲染颜色"))
        self.pushButtonSelectAllMeteorShowers.setText(_translate("MeteorShowerSelectionDialog", "全选"))
        self.pushButtonClearMeteorShowers.setText(_translate("MeteorShowerSelectionDialog", "清空"))
        self.pushButtonCancelMeteorSelection.setText(_translate("MeteorShowerSelectionDialog", "取消"))
        self.pushButtonAcceptMeteorSelection.setText(_translate("MeteorShowerSelectionDialog", "确定"))
