# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoralign/ui/preferences_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(860, 700)
        PreferencesDialog.setMinimumSize(QtCore.QSize(760, 560))
        self.verticalLayoutPreferencesDialog = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayoutPreferencesDialog.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutPreferencesDialog.setObjectName("verticalLayoutPreferencesDialog")
        self.widgetPreferencesContainer = QtWidgets.QWidget(PreferencesDialog)
        self.widgetPreferencesContainer.setObjectName("widgetPreferencesContainer")
        self.verticalLayoutPreferencesContainer = QtWidgets.QVBoxLayout(self.widgetPreferencesContainer)
        self.verticalLayoutPreferencesContainer.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutPreferencesContainer.setObjectName("verticalLayoutPreferencesContainer")
        self.verticalLayoutPreferencesDialog.addWidget(self.widgetPreferencesContainer)

        self.retranslateUi(PreferencesDialog)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "软件选项"))
