from __future__ import annotations

# 两点相似变换只用于单星自动匹配、双击聚焦和低精度预览。
MIN_PRELIMINARY_ALIGNMENT_PAIRS = 2
# 正式天球模型、自动扩展匹配和映射导出仍需要至少四对星点。
MIN_ALIGNMENT_PAIRS = 4
QUADRATIC_ALIGNMENT_PAIRS = 6
MAX_ALIGNMENT_CONDITION_NUMBER = 1e10
MAX_TRANSFORM_ABS_PX = 1e9
SKY_MATCHING_MODEL_ANCHOR_INTERPOLATION = "anchor_interpolation"
SKY_MATCHING_MODEL_POLYNOMIAL = "polynomial"
SKY_MATCHING_MODEL_RECTILINEAR = "rectilinear"
SKY_MATCHING_MODEL_FISHEYE_EQUIDISTANT = "fisheye_equidistant"
SKY_MATCHING_MODEL_FISHEYE_EQUISOLID = "fisheye_equisolid"
SKY_MATCHING_MODEL_STEREOGRAPHIC = "stereographic"
SKY_MATCHING_MODEL_MERCATOR = "mercator"
SKY_MATCHING_MODEL_CYLINDRICAL_EQUIDISTANT = "cylindrical_equidistant"
SKY_KNOWN_PROJECTION_MODELS = (
    SKY_MATCHING_MODEL_RECTILINEAR,
    SKY_MATCHING_MODEL_FISHEYE_EQUIDISTANT,
    SKY_MATCHING_MODEL_FISHEYE_EQUISOLID,
    SKY_MATCHING_MODEL_STEREOGRAPHIC,
    SKY_MATCHING_MODEL_MERCATOR,
    SKY_MATCHING_MODEL_CYLINDRICAL_EQUIDISTANT,
)
SKY_SKY_PLANE_INTERPOLATION_MODELS = (SKY_MATCHING_MODEL_ANCHOR_INTERPOLATION, SKY_MATCHING_MODEL_POLYNOMIAL)
SKY_MATCHING_MODELS = (*SKY_SKY_PLANE_INTERPOLATION_MODELS, *SKY_KNOWN_PROJECTION_MODELS)
PROJECTION_FIT_MAX_NFEV = 2000
PROJECTION_INVALID_RESIDUAL_PX = 1e6
RESIDUAL_CORRECTION_TPS = "thin_plate_spline"
ANCHOR_INTERPOLATION_TPS = "thin_plate_spline"
FIT_WEIGHT_MIN = 1e-6
FIT_WEIGHT_MAX = 1.0
SOFT_CONSTRAINT_TPS_SMOOTHING_BASE = 0.03
SKY_KNOWN_PROJECTION_DISPLAY_NAMES = {
    SKY_MATCHING_MODEL_RECTILINEAR: "普通透视镜头(TAN)",
    SKY_MATCHING_MODEL_FISHEYE_EQUIDISTANT: "等距鱼眼(ARC)",
    SKY_MATCHING_MODEL_FISHEYE_EQUISOLID: "等立体角鱼眼(ZEA)",
    SKY_MATCHING_MODEL_STEREOGRAPHIC: "立体投影(STG)",
    SKY_MATCHING_MODEL_MERCATOR: "墨卡托(MER)",
    SKY_MATCHING_MODEL_CYLINDRICAL_EQUIDISTANT: "等距圆柱(CAR)",
}
SKY_KNOWN_PROJECTION_CODES = {
    SKY_MATCHING_MODEL_RECTILINEAR: "TAN",
    SKY_MATCHING_MODEL_FISHEYE_EQUIDISTANT: "ARC",
    SKY_MATCHING_MODEL_FISHEYE_EQUISOLID: "ZEA",
    SKY_MATCHING_MODEL_STEREOGRAPHIC: "STG",
    SKY_MATCHING_MODEL_MERCATOR: "MER",
    SKY_MATCHING_MODEL_CYLINDRICAL_EQUIDISTANT: "CAR",
}

__all__ = [name for name in globals() if not name.startswith("__")]
